/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FloedeButton {
    }
    interface FloedeInput {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFloedeButtonElement extends Components.FloedeButton, HTMLStencilElement {
    }
    var HTMLFloedeButtonElement: {
        prototype: HTMLFloedeButtonElement;
        new (): HTMLFloedeButtonElement;
    };
    interface HTMLFloedeInputElement extends Components.FloedeInput, HTMLStencilElement {
    }
    var HTMLFloedeInputElement: {
        prototype: HTMLFloedeInputElement;
        new (): HTMLFloedeInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "floede-button": HTMLFloedeButtonElement;
        "floede-input": HTMLFloedeInputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FloedeButton {
    }
    interface FloedeInput {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "floede-button": FloedeButton;
        "floede-input": FloedeInput;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "floede-button": LocalJSX.FloedeButton & JSXBase.HTMLAttributes<HTMLFloedeButtonElement>;
            "floede-input": LocalJSX.FloedeInput & JSXBase.HTMLAttributes<HTMLFloedeInputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
